# start and show Excel, set/get ranges
library(rcom)
excel<-com.object.create("Excel.Application")
com.property.set(excel,"Visible",TRUE)
newwb<-com.invoke(com.property.get(excel,"Workbooks"),"Add")
ws<-com.property.get(newwb,"Worksheets",1)
com.property.set(com.property.get(ws,"Range","A1"),"Value","vertical range")
com.property.set(com.property.get(ws,"Range","A12"),"Value","horizontal range")
rng1<-com.property.get(ws,"Range","A2:A11")
rng2<-com.property.get(ws,"Range","A13:E13")
rng1.val<-rnorm(10)
dim(rng1.val)<-c(10,1)
rng2.val<-rnorm(5)
dim(rng2.val)<-c(1,5)
com.property.set(rng1,"Value",rng1.val)
com.property.set(rng2,"Value",rng2.val)
